version: 1.0.{build}

image: Visual Studio 2015

configuration: Release

# Configure both 32-bit and 64-bit builds
environment:
  matrix:
  - platform: x86
    config: Win32
    pout: x86
  - platform: x64
    config: x64
    pout: x64

shallow_clone: true

# Download Meson and Ninja, create install directory
before_build:
- mkdir output
- mkdir libmpdclient-shared-%pout%
- cd output
- curl -LsSO https://github.com/mesonbuild/meson/releases/download/0.39.1/meson-0.39.1.tar.gz
- 7z x meson-0.39.1.tar.gz
- move dist\meson-0.39.1.tar .
- 7z x meson-0.39.1.tar
- rmdir dist
- del meson-0.39.1.tar meson-0.39.1.tar.gz
- curl -LsSO https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip
- 7z x ninja-win.zip
- del ninja-win.zip
- cd ..

# Build and install
build_script:
- cd output
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
- C:\Python36\python.exe meson-0.39.1\meson.py .. . --backend=ninja --prefix=%APPVEYOR_BUILD_FOLDER%\libmpdclient-shared-%pout%
- ninja
- ninja install
- cd ..

test_script:
- ninja -C output test
