language: c

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - meson
            - ninja
            - check

before_install:
  - test "$TRAVIS_OS_NAME" != "osx" || export HOMEBREW_NO_ANALYTICS=1

install:

script:
  - OPTIONS="-Dtest=true"
  - meson . output $OPTIONS
  - ninja -v -C output test
