language: c

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - meson
            - ninja
            - check

before_install:

install:

script:
  - OPTIONS="-Dtest=true"
  - meson . output $OPTIONS
  - ninja -v -C output test
