dist: trusty
language: c

os:
  - osx

before_install:
  - test "$TRAVIS_OS_NAME" != "osx" || brew update

install:
  - test "$TRAVIS_OS_NAME" != "osx" || brew install meson ninja check

script:
  - OPTIONS="-Dtest=true"
  - meson . output $OPTIONS
  - ninja -v -C output test
